### ISSUE TITLE
Data transformation code problem

### ISSUE THREAD

**Issue by fbnhns** [jcheng5/shiny-js-examples#6]
Hi @jcheng5, 

thanks a lot for this working example of combining Shiny with nvd3 - much appreciated. 

I am currently looking to adapt this to my needs - which is displaying multiple time series. For that I tried to adjust this code in _linechart.R_: 

```
renderLineChart <- function(expr, env=parent.frame(), quoted=FALSE) {
  # This piece of boilerplate converts the expression `expr` into a
  # function called `func`. It's needed for the RStudio IDE's built-in
  # debugger to work properly on the expression.
  installExprFunction(expr, "func", env, quoted)
  
  function() {
    dataframe <- func()

    mapply(function(col, name) {

      values <- mapply(function(val, i) {
        list(x = i, y = val)
      }, col, 1:nrow(dataframe), SIMPLIFY=FALSE, USE.NAMES=FALSE)

      list(key = name, values = values)
      
    }, dataframe, names(dataframe), SIMPLIFY=FALSE, USE.NAMES=FALSE)
  }
}
```

I understand this function uses the row number as x value for all variables passed to it. However I'd like to have it use a column in the dataframe passed to it (which contains my date variables as js timestamps) but have failed miserably so far. Any suggestions on what might be the right way to achieve what I want to do?

**Comment by jcheng5** [comment]
Replace `1:nrow(dataframe)` with `dataframe[[date_col_name]]`. You’ll also have to change the outer mapply’s arguments so that it doesn’t include that date column in the set of series it creates.

**Comment by fbnhns** [comment]
Thanks so much for the fast response. I changed it to this  (the timestamp column is the first column in the dataframe): 

```
renderLineChart <- function(expr, env=parent.frame(), quoted=FALSE) {
  installExprFunction(expr, "func", env, quoted)

  function() { #this function converts R dataframe to
    dataframe <- func()

    mapply(function(col, name) {

      values <- mapply(function(val, i) {
        list(x = i, y = val)
      }, col, dataframe[[timestamp]], SIMPLIFY=FALSE, USE.NAMES=FALSE)

      list(key = name, values = values)

    }, dataframe[,-1], names(dataframe[,-1]), SIMPLIFY=FALSE, USE.NAMES=FALSE)
  }
}
```

However I get this error when I try to run the app: 

```
Warning: Error in vectbl_as_col_location2: Must extract column with a single valid subscript.
✖ Subscript `timestamp` has the wrong type `function`.
ℹ It must be numeric or character.
  100: <Anonymous>
```

**Comment by fbnhns** [comment]
accidentally closed, sorry about that

**Comment by fbnhns** [comment]
Using `dataframe$date_col_name`worked - thanks!
